version: '3'
services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todo_app
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
